### ISSUE TITLE
When you apply replace() method over pageStack in ApplicationWindow, Replaced page loses its QQuickStyle.

### ISSUE THREAD

**Issue by firatagdas** [lirios/fluid#100]
To Simplest Reproduce case:

On Fluid-Demo: Pages/Compound/ListItemPage.qml 
Change the line:

`onClicked: pageStack.push(model.source)`
to 
`onClicked: pageStack.replace(model.source)`

It will become from:

![1](https://cloud.githubusercontent.com/assets/153557/25775001/8d06b25a-32a3-11e7-88b6-01f8836bd597.png)

To: 

![2](https://cloud.githubusercontent.com/assets/153557/25775000/8d046f68-32a3-11e7-8905-068708075227.png)

**Comment by redgrapetech** [comment]
This affects me too . Its show stopping bug! please increase priority.

**Comment by redgrapetech** [comment]
thanks @plfiorini  , I spent almost half the day digging around , then i too realized that replace
was acting funny . Then i restructured my code based on push , but its difficult to avoid replace
on pageStack. Then i started scanning the issues here and found this one.

**Comment by plfiorini** [comment]
@redgrapetech @firatagdas Seems fixed here with 7c5fe32e34b5ba40c9bfd0a3496dc206a252cfb2
Can you give it a shot?

**Comment by firatagdas** [comment]
Yeap. That fixed. Thank you @plfiorini!

**Comment by plfiorini** [comment]
You are welcome

**Comment by redgrapetech** [comment]
Yep Fixed for my use case too . Thanks :+1:
