### ISSUE TITLE
Where is OverlayView?

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#101]
I am thinking about porting an application from qml-material to fluid, which used many OverlayViews.
I don't know whether you intentionally did not port OverlayView or just forgot it, so I am asking here.
Here is the OverlayView from qml-material: https://github.com/papyros/qml-material/blob/develop/src/components/OverlayView.qml
Would be really cool to have it in fluid too :)

**Comment by plfiorini** [comment]
I did not port it because it was looking like a Dialog.

**Comment by plfiorini** [comment]
Actually it's still useful because we don't need any padding so I quickly implemented it.

**Comment by plfiorini** [comment]
Thanks for the suggestion. Feel free to open a new issue if you need more features.
