### ISSUE TITLE
ApplicationWindow's actionbar keeps entries tinted after releasing the mouse

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#102]
When you add actions to the bar in an ApplicationWindow and click on an entry, it gets colored. However, when you release the mouse, it does not reset to its default appearance.
In the following image you see an example, I clicked on Help and on About and already released the mouse, but they are still colored as if I would still click on them. The Quit action does still have the default appearance.

![temp](https://cloud.githubusercontent.com/assets/21310755/26034771/f4137fa4-38c1-11e7-9dd7-757b80c0891b.png)

Btw on a related side note: It would be really cool to have a hover effect on these actions, like you have in a ListView with ListElements for example. Currently they only get colored when you click on them.

**Comment by magnus-gross** [comment]
I don't know if it is Qt 5.9 or if you forgot to reference this issue in a fix commit, but this issue seems to be fixed on my end with Qt 5.9.

**Comment by magnus-gross** [comment]
Still, a hover effect would be pretty cool...

**Comment by plfiorini** [comment]
@magnus-gross Can you reproduce the issue anymore?

I can't with `fluid-demo` and the overflow menu items have the hover effect now.

**Comment by magnus-gross** [comment]
The original issue is resolved.
However, I do not see a hover effect on my end...
Not even with latest Fluid on the Fluid demo.

**Comment by plfiorini** [comment]
Overflow menu items are `MenuItem` from QtQuick Controls 2, it might be an upstream bug so I'm closing the issue.
