### ISSUE TITLE
enhancement of guidelines  w.r.t submission of issues.

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#109]
We should be enhancing the contribution guidelines 
https://github.com/lirios/fluid/blob/develop/CONTRIBUTING.md

to say something about proper submission of Issues also . 

Rite now it is mostly a  code contribution guideline.

**Comment by rmallah** [comment]
Hi Pier
I have drafted the below , please feel free to use the text   for final drafting. 


===================================================================

Users are encouraged to take care of following aspects while reporting issues

(1) Be gentle 

We are volunteers  , most of us spare our family time and develop software 
primarily because of the love for it and for various other motivations. Kindly do 
not get demanding. It is difficult for us to set any water tight deadline
of fixing or developing something new. If you are in hurry and have skills
to program please consider contributing code.


(2) Do not say 'its not working' 

Developers are inherently objective and analytical. If a behaviour of the
software is not upto the expectation *explain in details* what is actually
happening , mostly it is useless to just say its not working. Eg if you are 
seeing  a blank screen , do not say you are seeing "nothing" it better to 
say you are seeing a blank screen.

(3) Do not be assuming without  a disclaimer 

If you are stating something be very sure about it , if you are *thinking* 
or assuming something make it clear that you assumed something.

(4) Give  specific examples *even* if you are referring to an universal set 

If a bug exists for a collection of input factors , try to give specific
instances of the input. Eg suppose a thing does not work for any of the users
, you should report that "the thing did not work for any of the users and
we tested it for sam and joe" . 


(5) Choose a proper subject 

Choosing a proper subject allows us to make a mental map when we glance 
over a list. We are quickly able to think about dependencies and priorites
in a glance. 

   5.1 A proper subject should be a one liner preferably less than 80 chars
   5.2 it should indicate the extent of the problem 
   5.3 it should summarize as comprehensive as possible.

(6) Provide a minimal replication procedure

   replicating a buggy situation for a developer is itself one of 
   the most demanding activities. Try to mention a clear path by which
   the problem can be repeated . try to think what would be easiest
   for the *developer* to replicate the problem at his/her end .
   It also helps to attach a zipped project that replcates the problem
   at your development environment . It is best to start with a new
   project and include elements into it leading to the problem.
   
(7) Provide details / evidences 
  
    It helps greatly to attach screenshot and videos of problem specially
    when you are referring to visual issues.

(8) keep the developers updated of any new observation regarding the issue.

   when you find a new observation , be kind enough to comment on the issue ,
   as it is mostly difficult to give immediate attention  , every bit of information
   and updates help when the bug is looked into at a later date.
   
(9) Report-back workarounds

    if you find a workaround for a issue please update the issue , so that
    others can use it as a temporari solution. It greatly helps developers also
    as sometimes the workarounds can be precursors to the formal solutions.



=====================================================================

**Comment by rmallah** [comment]
(10) Report Software versions & setup and tool chains etc
as far as possible report version of Qt  , build targets ( Android, windows , linux)  and software
environment in general.

TODO: this is just a stub , above  requires expansion and  refinement.

**Comment by plfiorini** [comment]
Done! Thanks!
