### ISSUE TITLE
autoclosing of NavigationDrawer on trigger

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#110]
If an action item belonging to NavigationDrawer  is triggered and the 
Drawer is currently open we may consider closing it .  Rite now
we are having to put it in every trigger code.

example code: (partial)
```
   actions: [
        FluidControls.Action {
            text: qsTr("Home")
            iconName: "action/home"
            enabled: Global.loggedIn
            onTriggered: {
               navDrawer.close(); // may be done in the fluid library
               pageStack.replace( Global.homePage() ) ;
            }
        },
        FluidControls.Action {
            text: qsTr("Concerns")
            iconName: "action/assignment"
            enabled: Global.loggedIn
            onTriggered: {
               navDrawer.close();  // may be done in the fluid library
               pageStack.push( Global.getPage(Global.nm_addConcern ) ) ;
            }
        }
]
```

**Comment by plfiorini** [comment]
I don't think actions should close `NavigationDrawer` automatically because `Action` would need to know whether it was created inside it and only in that case call `close()` before emitting `triggered` thus making actions do more than they are expected to do.
