### ISSUE TITLE
failed to build fluid and git submodules update --int on windows 

### ISSUE THREAD

**Issue by xdien** [lirios/fluid#113]
I don't how to describe problem. when  i running command.
`git submodule update --init`
> Submodule 'features' (git://github.com/lirios/qmake-features) registered for path 'features'
> Submodule 'qbs-shared' (git://github.com/lirios/qbs-shared) registered for path 'qbs/shared'
> Cloning into 'D:/nhansu/fluid/features'...
> Cloning into 'D:/nhansu/fluid/qbs/shared'...
> Submodule path 'features': checked out 'c65726d97f27dd7ee352f6593db7f79680990b5c'
> fatal: cannot create directory at 'modules/XCB/aux': Invalid argument
> Unable to checkout '2b6268cabe80d6de7327ab692eb653a826af5433' in submodule path 'qbs/shared'
> 
and build with command `mingw32-make -j5; ming32-make install`
> The system cannot find the path specified.
> Makefile.Release:337: recipe for target '../../../qml/Fluid/Controls/BaseListItem.qml' failed
> ....

**Comment by solarsail** [comment]
`aux` is a reserved name in Windows for some reason that dates back to the old DOS time. This will not build on Windows until that `XCB/aux` module is renamed, I suppose.

**Comment by plfiorini** [comment]
thanks @solarsail I will rename it somehow
