### ISSUE TITLE
Qbs build fails

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#123]
On my end the qbs build system does not seem to work. I tried opening with Qt Creator and manually building and it always fails with:
`ERROR: /home/magnus/Documents/Qt/fluid/src/fluid/fluid.qbs:3:1 Unexpected item type 'LiriModule'.`

**Comment by plfiorini** [comment]
type `git submodule update --init`

**Comment by magnus-gross** [comment]
Thanks, this solved the problem. Qbs does indeed look like a better build system...
Maybe consider adding a little note to the README, that this project requires the submodules to build? Since even a new clone wouldn't download the submodules without the `--recursive` flag, I would assume that many people would forget the submodules, simply because they don't know about it. Adding a little one-liner to the README could maybe save you answering more issues with the same topic, just saying ;)
