### ISSUE TITLE
Cannot Link qml File with Action

### ISSUE THREAD

**Issue by edips** [lirios/fluid#128]
I try to make an app using demo application. With main.qml:
```         
 Action {
                text: qsTr("Page2")
                id:locate
                iconName: "action/info"
                Loader { id: pageLoader }
                MouseArea {
                    anchors.fill: parent
                    onClicked: pageLoader.source = "Page2.qml"
                }
            }
```
Error is: 
```qrc:/LocationCalculus.qml:26:17: QML Subheader: Cannot anchor to an item that isn't a parent or sibling.```

**Comment by Aldrog** [comment]
Action is non-visual item (derived from QtObject). You cannot place visual items such as Loader and MouseArea (derived from Item) as it's children.
If you want to bind to click on icon representing the action use onTriggered handler.

**Comment by edips** [comment]
Thanks. I will research about it. If there is no way to open a new page with onTriggered i will take a look another alternatives of Action menu such as flat style examples in Qt5 which list components are used.

**Comment by plfiorini** [comment]
Make the `Loader` a child of your visual item and change page from `onTriggered` like so:

```qml
Rectangle {
    color: "green"
    width: 400
    height: 400

    Loader { id: loader; anchors.fill: parent; source "Page1.qml" }

    Action {
        onTriggered: loader.source = "Page2.qml"
    }
```

**Comment by rmallah** [comment]
Hi Pier,

can't we have a slack channel  for discussions . using "Issues" is an
overkill ?
shall I setup one ?

regds
mallah.

**Comment by tim-sueberkrueb** [comment]
@rmallah there's an [IRC channel](irc://chat.freenode.net:6667/liri).

**Comment by plfiorini** [comment]
There's also an IRC frontend that's kinda like Slack: https://riot.im/app/#/room/#liri:matrix.org
