### ISSUE TITLE
Build for Android

### ISSUE THREAD

**Issue by CheeryLee** [lirios/fluid#130]
Hello!
How can I build Fluid for using it for Android programms (including using the library as a separate Qt module)?

**Comment by edips** [comment]
Try [this script](https://gist.github.com/tim-sueberkrueb/bc60f3318878d6889622237cd19fc9db) if your OS is Ubuntu. If you use different distro delete those lines:
sudo apt update && sudo apt upgrade
sudo apt install git cmake extra-cmake-modules
sudo apt install mesa-common-dev # Required for android-cmake
save and run the script. Choose "Latest release" when version is asked.

**Comment by tim-sueberkrueb** [comment]
Hey @CheeryLee, are you using a Qt installation from the Qt online installers?
If you want to build the latest release (`v0.10.0`), follow @edips' instructions.
If you want to build the current development state:
```
cd fluid
mkdir build && cd build
<path/to/qt>/<android-kit>/bin/qmake> ../fluid.pro
make
make install
```

**Comment by yangxingpping** [comment]
How about on windows?

**Comment by tim-sueberkrueb** [comment]
@yangxingpping you might want to use the [per-project-installation](https://github.com/lirios/fluid#per-project-installation-using-qmake) because that will be less painful on Windows.

**Comment by plfiorini** [comment]
Per project installation was recently revamped.
There are a couple of examples now in `example/perproject`, specifically for Android you want `minimalqmake` since qbs does not offer all `androiddeployqt` features yet.
