### ISSUE TITLE
SearchBar acts weird on Mobile

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#158]
On mobile devices, the SearchBar only hides its placeholder text when the touch keyboard loses its focus from the TextField.

Here is a short gif to show what I mean: https://gfycat.com/gifs/detail/PeskyCorruptAzurevase

As you can see in the gif, the placeholder text does not disappear immediately when it should.

I am not quite sure, what would be the best way to resolve this problem. As you can see in [the source](https://github.com/lirios/fluid/blob/develop/src/imports/controls/SearchBar.qml#L181), the place holder text's visibility is simply bound to the search text field's text being empty.
Any ideas? @plfiorini 

Maybe it is time to switch back to Qt's native text field. However, I would have to fix the problem that I described [here](https://github.com/lirios/fluid/pull/98#issuecomment-299418295) about the native text field first.

**Comment by oKcerG** [comment]
I guess that using `displayText` instead of `text` would fix this issue.

**Comment by magnus-gross** [comment]
Yes, that does indeed work!
