### ISSUE TITLE
MacOS build: modules not found

### ISSUE THREAD

**Issue by AndreaDemontis** [lirios/fluid#160]
During the execution the osx version of minimalqmake and minimalqbs, the compiler doesn't copy the qml fluid folder inside the bundle .app folder. I temporarily fixed the problem by adding to the .pro file the following code:

```
macx
{
    APP_QML_FILES.files = $$OUT_PWD/../fluid/qml/Fluid
    APP_QML_FILES.path = Contents/MacOS
    QMAKE_BUNDLE_DATA += APP_QML_FILES
}
```

**Comment by plfiorini** [comment]
Added to the `minimalqmake` example thanks
