### ISSUE TITLE
DatePicker and TimePicker on moblie

### ISSUE THREAD

**Issue by QShen3** [lirios/fluid#163]
if not set height and width, their width may larger than the screen's width.

if scale them to adapt screen, would get this
![image](https://user-images.githubusercontent.com/3995336/32899010-b8c205ba-cb24-11e7-938a-af00323f37e1.png)
1920 * 1080 420dpi

**Comment by plfiorini** [comment]
@QShen3 Pickers are landscape by default but your phone is portrait. Have you tried setting the orientation property accordingly?

**Comment by QShen3** [comment]
@plfiorini After set the orientation to Qt.PortraitOrientation, it displays correctly

**Comment by plfiorini** [comment]
Ok so it's not a bug, although the `orientation` property could be set to the screen primary orientation by default.
