### ISSUE TITLE
QQmlExpression: Expression depends on non-NOTIFYable properties: QQuickIconLabel::color

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#177]
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:171:36 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:160:32 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:171:36 depends on non-NOTIFYable properties:
    QQuickIconLabel::color
QQmlExpression: Expression file:///usr/lib/qt/qml/Fluid/Controls/TabbedPage.qml:160:32 depends on non-NOTIFYable properties:
    QQuickIconLabel::color

Tell me if you need code snippets to reproduce this.
Used this fluid https://aur.archlinux.org/packages/fluid-git/
UPD. the same with current git version

**Comment by plfiorini** [comment]
This is caused by Qt Quick Controls 2 new changes.
I have a branch that is going to be merged in the new feature.

**Comment by plfiorini** [comment]
Fixed

**Comment by blok1118** [comment]
Hello. How to fix in old version (don't know version number) without updating?

**Comment by plfiorini** [comment]
You are required to use at least Qt 5.10, consider that the latest version is 5.15.
