### ISSUE TITLE
what's the value of lirideployment.qmlDir

### ISSUE THREAD

**Issue by sweord** [lirios/fluid#178]
Hi,
What's the value of lirideployment.qmlDir?

I can't find the definition of "lirideployment". When I search from the whole project, I can only find some dependence on it.

**Comment by plfiorini** [comment]
@sweord by default it is `"lib/qml"` (see https://github.com/lirios/qbs-shared/blob/develop/modules/lirideployment/lirideployment.qbs#L33)
