### ISSUE TITLE
Error: Cannot assign to non-existent property "canGoBack"

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#179]
file:///usr/lib/qt/qml/Fluid/Controls/PageStack.qml:54: Error: Cannot assign to non-existent property "canGoBack"
There is no such property in current (5.10.0) StackView

Everything works fine, just warning

**Comment by plfiorini** [comment]
When the `PageStack::currentItem` propery changes, the handler sets `canGoBack` on the item assuming it is a `Page` from Fluid. You are probably adding a non-Page to the stack.

The handler should check if the `currentItem` inherits from Fluid's `Page` instead of a warning.

**Comment by luntik2012** [comment]
Yes, it was standard qt's Page
Problem disappeared after import Fluid.Controls 1.0

**Comment by rmallah** [comment]
Hi Luntik ,

I strongly recommend to import Fluid in a separate namespace for clarity.
eg:

import Fluid.Controls 1.0 as FluidControls;

FluidControls.Page {


.......

}

this removes the confusion of which Page!  (Qt's or Fluid's)

regds
mallah.
