### ISSUE TITLE
TabbedPage improvements

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#180]
Is it possible to avoid active-but-invisible Tabs when they are not current tabs in TabbedPage? It will be rendered faster (http://doc.qt.io/qt-5/qtquick-performance.html). May be some bool property in TabbedPage to control/not control tabs visibility?

Also sometimes it's needed to know if tab visible (e.g. I can add identical shortcuts to all tabs and set enabled: visible to them).

For now I need to do this o_O

Tab {
	id: root
	visible: root == mainWindow.pageStack.currentItem.selectedTab

Also is it possible to create "tabs" property (like actions) in TabbedPage instead of directly creating tabs in TabbedPage body? Again, I cannot add shortcut in TabbedPage body to switch tabs...

**Comment by plfiorini** [comment]
What you probably want is a [StackView](https://doc.qt.io/qt-5/qml-qtquick-controls2-stackview.html) and a [TabButton](https://doc.qt.io/qt-5/qml-qtquick-controls2-tabbutton.html).

Something like:

```qml
TabBar {
  TabButton {
    text: stack.currentItem.text
  }
}

StackView {
  id: stack
  width: 200
  height: 200
  initialItem: Item {
    property string text: "Hello"
    Button {
      onClicked: stack.push(someComponent)
    }
  }
}
```

**Comment by plfiorini** [comment]
@luntik2012 Does it work for you?

**Comment by luntik2012** [comment]
I thought to use Fluid's window with it's features and it's StackView. No idea why to use another if there is already one.

**Comment by plfiorini** [comment]
Because you want a tabbed view without showing any tab and that's a stack view, if you want to use a tabbed page you have tabs visible by design.

**Comment by plfiorini** [comment]
@luntik2012 Example updated
