### ISSUE TITLE
FluidControls.IconButton docs 

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#182]
is FluidControls.IconButton supposed to be for enduser usage or an internal component.
In case of former we do not see any doc page for the same.

**Comment by plfiorini** [comment]
`FluidControls.IconButton` has evolved into `FluidControls.ToolButton`. All the icon stuff has been replaced by the new `icon` grouped property of QQC2 but I have added the `hoverAnimation` for actions.

`FluidControls.ToolButton` is documented, see: https://liri.io/docs/sdk/fluid/develop/qml-fluid-controls-toolbutton.html
