### ISSUE TITLE
SearchBar needs rewriting?

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#188]
For now it is unaligned something with huge text and has strange behaviour (and open animation). May be its background color set to `Material.accent` to replace `ToolBar` with SearchBar, but they have different `height`s.
Do you have some contributing rules? Or just pr? I'd like to implement it.
Just leaving it here: https://material.io/guidelines/patterns/search.html#

**Comment by magnus-gross** [comment]
What exactly is unaligned? On my end it looks fine.
Maybe post a screenshot to show us what you mean

**Comment by luntik2012** [comment]
Just compare it with link above. "Search" must be moved up.
![image](https://user-images.githubusercontent.com/8270543/34761971-05016c98-f5f7-11e7-91ca-d5a957a76b36.png)
Also, entered texts font size is too huge, but vertically centered.
![image](https://user-images.githubusercontent.com/8270543/34762009-32284d7c-f5f7-11e7-846a-abd046542541.png)

**Comment by luntik2012** [comment]
This should solve alignment issue, but why font size is so huge? May be I'm wrong and it's normal.
SearchBar.qml:

Label {
                    text: searchPlaceHolder
                    visible: searchTextField.displayText === ""
                    anchors.fill: searchTextField
			**verticalAlignment: Text.AlignVCenter**
                    font.pixelSize: searchTextField.font.pixelSize
                    color: Material.color(Material.Grey, Material.Shade400)
                }

**Comment by magnus-gross** [comment]
That's definitively weird.
The bad thing is that this problem is not happening on my computer. It probably has to do something with the fact that we use very custom controls for the placeholder text, see https://github.com/lirios/fluid/pull/98#issuecomment-299418295
I will look into it

**Comment by magnus-gross** [comment]
Unfortunately in the case of the Search Material design spec, there is no font size specified to be used with a search bar. What font size would you think would be better suited?

**Comment by luntik2012** [comment]
It seems "Search" word must have the same font size as TitleLabel. Don't know what with entered text

**Comment by magnus-gross** [comment]
And yes, if you want to contribute, this is done by a PR.
See https://github.com/lirios/fluid/blob/develop/CONTRIBUTING.md for more info.

**Comment by luntik2012** [comment]
> The bad thing is that this problem is not happening on my computer.
Please, try with `verticalAlignment: Text.AlignVCenter` on your computer. I think it will look as good as this
![image](https://user-images.githubusercontent.com/8270543/34762480-fd464f08-f5f8-11e7-9641-fed71dc5561e.png)

**Comment by magnus-gross** [comment]
The entered text should match the font size of the placeholder text ("Search")

**Comment by luntik2012** [comment]
>And yes, if you want to contribute, this is done by a PR...
Thank you

**Comment by magnus-gross** [comment]
> Please, try with verticalAlignment: Text.AlignVCenter on your computer. I think it will look as good as this

Yes, can confirm that it does.

**Comment by luntik2012** [comment]
Alignment is ok now. I don't know what font size will be ok, so closing this.
