### ISSUE TITLE
Make icons in resources optional

### ISSUE THREAD

**Issue by plfiorini** [lirios/fluid#196]
Icons in resources are easier to manage but increase the executable size.
Consider adding an option to switch between the two.

**Comment by JakeStoeffler** [comment]
@plfiorini Is the fluid project and Liri in general still active? I would like to get involved, particularly on the UI/QML side of things. But I noticed that the Wiki tab is gone at https://github.com/lirios/lirios/wiki and I couldn't find much information about what features/bugs are priorities and how I can contribute. I couldn't find a gitter room either. Any info is appreciated!

**Comment by plfiorini** [comment]
@JakeStoeffler Of course it's still active, as it's demonstrated by the git activity.
The wiki is being moved to https://liri-dev.readthedocs.io/en/latest/ and you can join us at ```#liri``` on Freenode or https://riot.im/app/#/room/#liri:matrix.org
