### ISSUE TITLE
IconThemeImageProvider returns a null icon on MacOs

### ISSUE THREAD

**Issue by pasdam** [lirios/fluid#198]
On MacOs the IconThemeImageProvider returns a null icon.

## Possible Solution

A possible workaround could be to use a [fallback icon](https://doc.qt.io/qt-5/qicon.html#fromTheme-1).

## Steps to Reproduce (for bugs only)

Open the demo app on MacOs, go to the `Style` tab and click on `System icons`. The following errors appear in the console:
```
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/accessories-text-editor
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/accessories-dictionary
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/accessories-character-map
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/accessories-calculator
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/system-users-symbolic
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/system-software-install-symbolic
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/weather-few-clouds-symbolic
file:///<build_dir>/fluid/Desktop_Qt_5_10_0_clang_64bit2/Debug/qtc_Desktop_Qt_5_10_0_clang_64bit2_Debug/install-root/qml/Fluid/Controls/Icon.qml:173:5: QML Image: Failed to get image from provider: image://fluidicontheme/text-editor-symbolic
```

## Environment

* Version used: 8c6b427ff6936ac4525c935f6ecbbb9c120648be;
* Operating system and version: macOS 10.13.

**Comment by plfiorini** [comment]
macOS doesn't have freedesktop.org icon themes so that's normal.
Yeah we could add a fallback icon in the resources, like the `unknown` icon from the `hicolor` theme.

**Comment by plfiorini** [comment]
After thinking about for a while I don't see this as a bug.
macOS doesn't have freedesktop.org icon themes normally (I guess that you can install a theme manually) and that is not a Fluid bug.
A fallback icon to work would need to be embedded in to the Fluid resources increasing the executable size for no real benefit.

**Comment by pasdam** [comment]
Well the benefit would be that the library would be cross platform.
A possible workaround could be to add the fallback icon only for platforms that don't have the theme.

**Comment by plfiorini** [comment]
Fluid is using QIcon which is part of Qt, does it make Qt not cross platform?
Besides we are talking about the demo program which is still cross-platform just like Fluid, it's just the "System icons" section that is showing a demo of something that not all systems have.

**Comment by pasdam** [comment]
I don't think is a fair analogy: of course QIcon is cross platform, but using system icons is not.
I'm not trying to argue, or convince you to fix it or anything, I just wanted to point out what is the benefit IMHO.
Also, at the moment I don't have a mac so I can't verify, but wouldn't it mean that on other system (not Linux) I can't use the embedded icons?
```
FluidControls.Icon {
    name: "text-editor-symbolic"
}
```
I didn't dive deep into the code, so please correct me if I'm wrong.

**Comment by plfiorini** [comment]
Sorry I meant `QIcon::fromTheme()`. Technically it can work on every operating system but it needs a freedesktop.org icon theme installed that on macOS and Windows is not installed by default but it can be installed, as the [documentation](http://doc.qt.io/qt-5/qicon.html#fromTheme) says:

```
Note: By default, only X11 will support themed icons. In order to use themed icons on Mac and Windows, you will have to bundle a compliant theme in one of your themeSearchPaths() and set the appropriate themeName().
```

Adding a fallback icon in Fluid doesn't change much as you will ever see that fallback icon every time an icon from the theme is requested, without knowing why while an error makes it more obvious that there is something to be done. Hence the fallback icon is a half measure that does more harm than good.

What would change things instead is if we bundle an icon theme ourselves but that would make all Fluid apps heavy, and the app developer might not like the theme we chose.
Besides Fluid already deals with cross-platform icons: those from the Material Design library will work on each and every platform.

If your application relies on freedesktop.org icons than you are doing something that goes beyond defaults and should be handled by yourself.

**Comment by pasdam** [comment]
Definitely adding a fallback icon is not the best solution, it was more a workaround, but I agree that it will probably do more harm then good. On the other hand I disagree that showing an error is better (at least an error message hidden in the console), as the user most likely won't notice it and he will think that there is a bug. Because of that, I would say that maybe it's better to show a message like "Sorry this feature is not available on your platform" in the app itself.
About making the app heavier, if it's just the demo app I think it's ok, but of course if we're talking to embed the theme in the core library itself then you're completely right, not a good idea for sure.

**Comment by plfiorini** [comment]
In the demo app we can add the "Sorry this feature is not available on your platform" text if the OS is macOS or Windows.

**Comment by plfiorini** [comment]
This is how it looks:

<img width="1280" alt="screen shot 2018-08-21 at 17 31 56" src="https://user-images.githubusercontent.com/843710/44411997-22925f80-a568-11e8-9ba1-91d07cdf8008.png">

It still tries to load the icons because the user might have installed a freedesktop.org icon theme.
Console still shows the image provider error if he hasn't installed a theme, but the label explains that the feature might not be available.
