### ISSUE TITLE
Per-project Installation doesn't work on IOS Simulator

### ISSUE THREAD

**Issue by edips** [lirios/fluid#204]
When I try running per-project installer qmake example it gave errors like ' "Fluid.Controls" is not installed.' and Simulator was blank paged. Interestingly the example works on OSX without error. I don't have IOS device so I didn't test on it.
On MacOs Sierra with Virtualbox.

**Comment by plfiorini** [comment]
This is fixed by recent commits, see also #131

**Comment by edips** [comment]
Thank you. I will try it soon.
