### ISSUE TITLE
Static build does not work

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#219]
If I use the per project installation of fluid, everything works fine until I try a static build. If I use a static build, it just says that all the QML imports are not available (like Fluid.Controls and so on).

Any idea what we have to change to make static builds possible? It seems, like Fluid is not properly bundled with static builds.

Exact error message is:
```
QmlApplicationEngine failed to load component
qrc:/main.qml:6 module "Fluid.Core" is not installed
qrc:/main.qml:5 module "Fluid.Controls" is not installed
qrc:/main.qml:6 module "Fluid.Core" is not installed
qrc:/main.qml:5 module "Fluid.Controls" is not installed
```

**Comment by hendrenja** [comment]
What is the recommended workaround for this when deploying a static application?
Is it to deploy using a "system-wide installation"? - That is the route that I am currently pursuing after hitting the same errors as called out by @magnus-gross.

I am under the impression that my system-wide install is properly configured as I am able to load the QML using:

```c++
QQmlApplicationEngine engine;

engine.addImportPath( "qrc:/" );
engine.addImportPath( "file:/usr/lib/qt/qml" );
engine.addImportPath( "file:/usr/lib/qt/qml/Fluid" );
```

However, I am still receiving the following error:

```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:4 module "Fluid.Controls" plugin "fluidcontrolsplugin" not found
```

I am linking with the plugins like:
```
LIBS += -L/usr/lib/qt/qml/Fluid/Controls
LIBS += -lfluidcontrolsplugin
```

**Comment by magnus-gross** [comment]
I am pretty sure, it was working when qmake was the default build system. I don't know what happened that qbs became the default build system, since it's clearly not working completely right now to be honest.

**Comment by plfiorini** [comment]
I have never used Qt static builds until today due to iOS support.
Qt for iOS is static and I had to do a few things, please see this commit: 08e92bd83e8e535c0a0a73e711bc676deae95e73 where I made iOS builds work.

The same could probably be extended to static builds, regardless of the operating system.

**Comment by hendrenja** [comment]
Hi @plfiorini, Thank you for the follow-up!

**Comment by plfiorini** [comment]
@magnus-gross @hendrenja Does PR #268 work for you?

**Comment by magnus-gross** [comment]
Just spent 3 hours building a new static Qt, but yeah, thanks a lot, it does indeed work now. :)

It didn't show any icons for me though, but I am not sure if this is a problem with Fluid or a problem of API changes that I didn't follow in my application, so I guess this should be solved now.

**Comment by plfiorini** [comment]
@magnus-gross Just built for iOS and couldn't reproduce this issue.
However `fluid/src/imports/core/utils.h` is an old file that doesn't exist anymore.
It got renamed in e66a938b237d56828f77463af2198029a83eac30, perhaps you didn't make a full clean of your build.
