### ISSUE TITLE
Demo does not run

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#223]
I can't get the demo to run with the latest version, neither CLI nor with Qt Creator.
Building works fine, but trying to run produces the following error:

```
qbs -d build -j $(nproc) profile:qt-5-10-1 && qbs run --no-build -d build --products fluid-demo
Restoring build graph from disk
Building for configuration default
Build done for configuration default.
Restoring build graph from disk
Installing
ERROR: /home/magnus/Documents/Qt/fluid/qbs/shared/modules/lirideployment/lirideployment.qbs:47:196 Error running setupRunEnvironment script for product 'fluid-demo': ReferenceError: Can't find variable: binDir
```

**Comment by nickdiego** [comment]
I also got this same issue some days ago. Just opened [this PR](https://github.com/lirios/qbs-shared/pull/28). It fixes this issue for me. Not sure if that's the "right" way to fix though :)

**Comment by plfiorini** [comment]
This has changed since qbs 1.11: https://bugreports.qt.io/browse/QBS-744

**Comment by matzrm** [comment]
hi,

I would to build the fluid-demo but I'm getting "product is not recognized". How to resolve? 
I have to install another version of qbs?
