### ISSUE TITLE
Multiple Definitions error

### ISSUE THREAD

**Issue by Collinthegeek** [lirios/fluid#236]
Build fails on Fedora 28

$ qbs build --no-install -d build profile:qt5 modules.lirideployment.prefix:/usr modules.lirideployment.qmlDir:/usr/lib/qt/qml
...
ERROR: /usr/bin/g++ -Wl,-m,elf_x86_64,-rpath,/usr/lib64 -L/usr/lib64 -m64 -o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/fluid-demo /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/3a52ce780950d4d9/iconcategorymodel.cpp.o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/3a52ce780950d4d9/iconnamemodel.cpp.o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/3a52ce780950d4d9/main.cpp.o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/3a52ce780950d4d9/qrc_fluid-demo.cpp.o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/73489b871e127538/moc_iconcategorymodel.cpp.o /home/cnorwood/git/fluid/build/default/fluid-demo.621c3a4a/73489b871e127538/moc_iconnamemodel.cpp.o /usr/lib64/libQt5Core.so.5.10.1 /usr/lib64/libQt5Gui.so.5.10.1 /usr/lib64/libQt5Network.so.5.10.1 /usr/lib64/libQt5Qml.so.5.10.1 /usr/lib64/libQt5Quick.so.5.10.1 /usr/lib64/libQt5QuickControls2.so.5.10.1

ERROR: //usr/lib64/libQt5QuickTemplates2.so.5:(*IND*+0x0): multiple definition of `_end'
//usr/lib64/libQt5QuickTemplates2.so.5:(*IND*+0x0): multiple definition of `__bss_start'
collect2: error: ld returned 1 exit status
ERROR: Process failed with exit code 1.
The following products could not be built for configuration default:
fluid-demo

**Comment by plfiorini** [comment]
It's a known Fedora 28 error from binutils: https://bugzilla.redhat.com/show_bug.cgi?id=1458003
The update was delayed and we have to wait a few days: https://bodhi.fedoraproject.org/updates/FEDORA-2018-ddd80a6dbb or you can download and install the RPM from Koji

**Comment by plfiorini** [comment]
Koji: https://koji.fedoraproject.org/koji/packageinfo?packageID=310

**Comment by plfiorini** [comment]
Closing, upstream bug is fixed.
