### ISSUE TITLE
Unable to use Fluid in QtCreator on Linux

### ISSUE THREAD

**Issue by daljit97** [lirios/fluid#256]
I cannot seem to make Fluid work inside my project. I have cloned Fluid inside my project folder, then I used INCLUDEPATH and QML2_IMPORT_PATH to include the necessary folders. I also tried with qputenv("QML2_IMPORT_PATH", "fluid/qml"), but nothing works (I always get `Fluid.Controls is not installed`). I am on Linux. I have checked the previous issues on this topic but none of them seems to work.

**Comment by obeezzy** [comment]
@daljit97 , have you tried "make install"?

**Comment by daljit97** [comment]
Ok so I did that and then I added all the fluid/qml files into the qrc of my app. But now I get the following error: ```
QQmlApplicationEngine failed to load component
qrc:/main.qml:3 module "Fluid.Controls" plugin "fluidcontrolsplugin" not found
```

**Comment by luntik2012** [comment]
could you show full project?

**Comment by edips** [comment]
AFAIK qbs doesn't work for Android. To install Fluid for Android:
```
export ANDROID_NDK_ROOT=/home/.../android-ndk-r10e
cd fluid
mkdir build && cd build
<path/to/qt>/<android-kit>/bin/qmake ../fluid.pro CONFIG+=install_under_qt
make
make install
```

**Comment by plfiorini** [comment]
Unfortunately qbs doesn't provide the `*deployqt` features yet.
In the future I would like to see if I can at least wrap `androiddeployqt` and solve that temporarily, until qbs provides a solution itself.

**Comment by plfiorini** [comment]
@daljit97 Did you see the example on how to integrate Fluid in your qmake project?
See https://github.com/lirios/fluid/tree/develop/examples/perproject/minimalqmake

**Comment by DevDorrejo** [comment]
> Ok so I did that and then I added all the fluid/qml files into the qrc of my app. But now I get the following error:
> 
> ```
> QQmlApplicationEngine failed to load component
> qrc:/main.qml:3 module "Fluid.Controls" plugin "fluidcontrolsplugin" not found
> ```

That error appear because you don't have one of the dependencies installed:

https://github.com/lirios/cmake-shared
