### ISSUE TITLE
C++ Date utilities

### ISSUE THREAD

**Issue by plfiorini** [lirios/fluid#26]
Sort of https://github.com/papyros/protoshell/blob/master/modules/Papyros/Desktop/qml/dateutils.js

But written in C++

**Comment by plfiorini** [comment]
@iBeliever Can I relicense this to MPL2?

**Comment by iBeliever** [comment]
@plfiorini Certainly :+1:

**Comment by plfiorini** [comment]
Rewrite the code introduced with be4f1d8 in C** for more performance
