### ISSUE TITLE
Can we use this library to create native apps in linux and windows?

### ISSUE THREAD

**Issue by navneetccna** [lirios/fluid#264]
I was wondering that can we install and use in linux OS to create cool apps? Can you please provide instructions to install it on Linux with QT5?

I am using Ubuntu 18.03 and QT5 Creator to build Desktop apps (Cross platform window applications).

**Comment by rmallah** [comment]
Sure that is what it is meant for. Including iOS

**Comment by navneetccna** [comment]
I tried Open up fluid.qbs with QtCreator, hit build and run to see the demo in action.

But getting following error

ERROR: fluid/src/imports/core/core.qbs:3:1 Unexpected item type 'LiriQmlPlugin'.

**Comment by navneetccna** [comment]
@rmallah Thank you for quick response can you guide me it install it?

**Comment by rmallah** [comment]
Yeah setting it up  may be a bit of struggle initially .
But its  ( the installation) is getting better .

Pls provide details of your Qt installation ,
eg is it distribution bundled ? , ( its recommended to use latest Qt
downloaded from
https://download.qt.io/official_releases/qt/5.11/5.11.1/

Sorry for not being able to provide precise answer to your
problem , but keep patience , some kind soul would help soon.

I use Fluid throughly in most of my Qt based mobile apps. It Works!

regds
mallah.

**Comment by magnus-gross** [comment]
What, no this is not Windows, you do not have to install Qt from the website like a barbarian.
Your Qt from the distro repos is fine and the preferred way.

There may be something wrong with the fluid project file, however can you try the following in the command line at the root of the repository:

```bash
qbs build profile:qt-5-11-1
qbs run --products fluid-demo
```

If qbs does not yet have the build profile qt-5-11-1, then please run `qbs setup-qt --detect` first and use the profile that qbs generated.

This works on my system and it should work on your system too.

**Comment by magnus-gross** [comment]
@navneetccna Actually, also make sure, that you have cloned the repository with all the submodules. I think, the problem is that you are missing a submodule. To fix this, please run `git submodule update --init` in the root of the repository, after that you can try the GUI approach with QtCreator again.

**Comment by navneetccna** [comment]
@magnus-gross I am able to run the demo and its working fine just some design issues on linux. The demo is not same as in git repo. Every thing else is working fine.

**Comment by magnus-gross** [comment]
What kind of design issues? Can you post a screenshot please?

**Comment by navneetccna** [comment]
@magnus-gross 

Tabs are missing

![screenshot from 2018-08-27 10-13-38](https://user-images.githubusercontent.com/210475/44640885-ee90c180-a9e1-11e8-88ab-8f4b8c1e236a.png)

**Comment by magnus-gross** [comment]
It is intended to look like this. The screenshot in the readme is not quite up to date. I think the issue can be closed now.

**Comment by navneetccna** [comment]
Ok, thanks for the help

**Comment by navneetccna** [comment]
That would be great what we can expect in 1.1 ?

**Comment by navneetccna** [comment]
That would be great what we can expect in 1.1 ?

**Comment by plfiorini** [comment]
@navneetccna At least one month from now
