### ISSUE TITLE
NavigationListDrawer is empty

### ISSUE THREAD

**Issue by edips** [lirios/fluid#266]
I would ask this question to liri's irc but I couldn't join there. When running my app on Simulator, NavigationDrawer is empity without actions. I am running High Sierra on Virtualbox. Is it because of 3D acceleration of OpenGL problem of VirtualBox? Because Qt's Gallery example's action menu also works too slow.
![untitled](https://user-images.githubusercontent.com/3856713/44958908-8feeaa80-aeef-11e8-9a9f-aa042a2a8785.png)

**Comment by plfiorini** [comment]
Due to freenode spam I had to allow only registered nicks.
If you join from matrix and didn't identify with NickServ, the channel will kick you out.

**Comment by edips** [comment]
Yes I saw there are many spams . I tried both, riot and freenode, I couldn't join there.

**Comment by plfiorini** [comment]
There is no reason it shouldn't work on real hardware, virtualization might have some issues.
I will check with my macBook soon.

**Comment by plfiorini** [comment]
You should register your IRC nickname: https://freenode.net/kb/answer/registration

**Comment by edips** [comment]
Thanks. I will try.

**Comment by edips** [comment]
I also tested it with desktop(clang), there was no action button. Only part of above "Menu" text seen. I tested [this example](https://liri.io/docs/sdk/fluid/develop/qml-fluid-controls-navigationlistview.html) from fluid documentation, only image appeared, but there wasn't action button. Action buttons were working on MacOS Virtal Box with Fluid 1.0 version

**Comment by plfiorini** [comment]
Reproduced and fixed it.

**Comment by edips** [comment]
Thank you @plfiorini ! It works nice :) At least I get my app working for IOS. I think to publish it for App Store after #267 is solved :)
