### ISSUE TITLE
Unable to upload a fluid app to App Store

### ISSUE THREAD

**Issue by renom** [lirios/fluid#267]
The error log:
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Core/libfluidcoreplugin.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Templates/libfluidtemplatesplugin.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Controls/libfluidcontrolsplugin_debug.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Core/libfluidcoreplugin_debug.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Controls/Private/libfluidcontrolsprivateplugin.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Templates/libfluidtemplatesplugin_debug.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Controls/libfluidcontrolsplugin.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.
> 
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'src.app/qml/Fluid/Controls/Private/libfluidcontrolsprivateplugin_debug.a' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> An unknown error occurred.

The screenshot:
<img width="732" alt="2018-09-10 8 19 37" src="https://user-images.githubusercontent.com/4979122/45277924-472c8800-b4d3-11e8-8853-72ecc41a9ecf.png">

**Comment by renom** [comment]
Hi. Is there any chance to resolve this issue in the near future? Thank you.

**Comment by plfiorini** [comment]
Sorry I'm late but I'm looking into it right now.
I want to close the iOS story for 1.1.0

**Comment by plfiorini** [comment]
@renom Please try now. Perform a complete clean and remove the build directory before trying.

**Comment by renom** [comment]
@plfiorini Now I have a blackscreened app :-(. To reproduce it, export an .ipa file, and manually install it to the device. I use diawi.com for manual installing. The app properly works (using the same method to install the app) if I use src.pro from this commit, but App Store refuses it (as I meant above). I had the same behavior when I excluded all the .a files from the output .ipa file, and then tried to publish the app (I did it at the beginning of September). The automatic tests were passed, but as a result of app review the app was rejected. The reason was the blackscreened app.
PS If I build & run the app from the Qt, the app properly works on the simulator, but it doesn't properly work if export & manually install the .ipa file.

**Comment by plfiorini** [comment]
Do you see any output that can help us figure out what's going on?
What about launcing the app with QT_DEBUG_PLUGINS=1?

**Comment by renom** [comment]
I had this behavior when running the app on a real device (not a simulator). So I don't know the way how to get the app output or any logs in that case (and also how to set up environment variables). I'll try to find some info, but if somebody know how to do it, please let me know :-).

**Comment by plfiorini** [comment]
You can run apps on your device from QtCreator: http://doc.qt.io/qtcreator/creator-developing-ios.html
I don't have first hand experience on iOS because I only have Android devices.

And apparently you can also configure the simulator with a particular iOS version.
See if setting the same iOS version as your physical device the black screen issue can be reproduced.

**Comment by renom** [comment]
Ok, I've got the error log:
> 08:27:33.724615 +0300	src	Retrieving resting unlock: 0
> 08:27:34.041785 +0300	src	QQmlApplicationEngine failed to load component
> 08:27:34.041892 +0300	src	qrc:/qml/main.qml:25 module "Fluid.Controls" is not installed
Also, I've found another strange behaviour. If I use "export & install the .ipa file" method or if I run the app from Xcode, the issue takes place. But if I run the app from Qt Creator, the app works fine. In all the described cases I've tried to run the app on iPad Air 2.

**Comment by plfiorini** [comment]
This could be related to QML plugins, see this instruction: https://github.com/lirios/fluid/blob/develop/src/imports/controls/qmldir#L2
Builds on iOS are static so there is no plugin to load.

Could you try again removing all `plugin` instructions from all `qmldir` files?

**Comment by renom** [comment]
But if I manually install the .ipa file, I get the previously mentioned error - "module "Fluid.Controls" is not installed".

**Comment by renom** [comment]
What I've found just now - the "module "Fluid.Controls" is not installed" error occurs only if the output .ipa file doesn't contain any of Fluid qml files. I'm not sure what impact on it. But in some cases the src.app/qml/Fluid folder contains only the Controls/icons/ path with the .svg icons. In other cases this folder contains all the proper folders (Core, Controls, Effects, Layouts and Templates) with all the files (e.g. .qml files, qmldir files). I'll try to figure out if something related with that.

**Comment by renom** [comment]
So, everything is OK when I've done build & run from Qt Creator before doing build & run (or exporting an .ipa) from Xcode. The blackscreen appears if I've only done build (without run) from Qt Creator. I'll try to use this knowledge to publish the app to App Store.

**Comment by renom** [comment]
Ok guys, the app have been approved. A little manual how to publish an iOS app:
1. You need a properly configured project. See the ios section of the src/src.pro file of the minimalqmake example.
2. You also need an Info.plist file, an Images.xcassets catalog with icons and launch images.
3. Install Qt & Qt Creator, clone the project repository, run Qt Creator, open the project.
4. Go to the Projects tab -> Qt for iOS (or Qt for iOS Simulator, if you don’t have a real device) -> Build. Select the release build configuration.
5. Do Run (not Build). Wait for the app to run.
6. Run Xcode. Select Open another project, go to the build dir, find & open the .xcodeproj file (for the minimalqmake example, it’s inside the src subfolder).
7. Make some publishing settings (e.g. setting up provisioning profile).
8. Go to Product -> Archive. Wait until completed. You’ll see a window with a list of archives.
9. Select Distribute App, select Ad Hoc and export an .ipa.
10. Extract the .ipa file, cd to src.app.
11. Check if the qml/Fluid folder contains all the proper folders (Controls, Core, Effects, Layouts, Templates). If it doesn’t, repeat all the steps from 5.
12. Select Distribute App again, select iOS App Store. Upload the app to App Store.

**Comment by rmallah** [comment]
Thanks Nikita for posting documentation.
Much appreciated.

regds
Rajesh Mallah.

**Comment by plfiorini** [comment]
Thanks! I'm preparing Liri for the 1.1.0 release then.
