### ISSUE TITLE
NavigationListView is not working with Qt.5.12

### ISSUE THREAD

**Issue by rawda85** [lirios/fluid#275]
NavigationListView has a list of items where you can click or hover by mouse which is working will in Qt.5.10
When upgrading to the newer version of Qt.5.12, The items in the list are not clickable anymore and do not respond to user actions. 

This happens to the current fluid demo when building with Qt.5.12. Then after running the demo, if you clicked on NavigationListView, the list shown is not responding.

Qt Creator has an example called Side Panel, which has a Drawer with List view similar to NavigationListView in fluid. However it works fine in the example. So I do not think there a problem in Qt itself, but they probably require some properties to be changed.

I am using Visual Studio 2017 64bits, Windows 10.

**Comment by rawda85** [comment]
I have upgraded to 5.12.1 version and the results are better. The menu is working again. It seems this is a bug in Qt 5.12.0 that was solved. It is just the width of the label is shorter but I guess that is easy to solve.

![menu](https://user-images.githubusercontent.com/13153646/52402530-c9da6300-2ac4-11e9-966d-e9a4e74cecb4.PNG)

**Comment by luntik2012** [comment]
Do you use custom `ItemDelegate`? Width is ok with 5.12.2 (linux/win7)/Fluid 1.1.0 (93e4ccc and newer). Your bug looks like this:
```qml
delegate: ItemDelegate {
    text: modelData.text
//  width: navigationListView.width
    icon.source: modelData.icon.source
}
```

**Comment by plfiorini** [comment]
Just made a change to make sure the standard delegates also set `width` to the list view `width` property.
Can't test on Qt 5.12 right now (still 5.11 here).
