### ISSUE TITLE
Minimal cmake example broken

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#281]
I think, the minimalcmake example is broken. When I run `cmake .. && make` inside a build folder and then start to run the executable in `src/example`, it says:

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:4 module "Fluid.Controls" is not installed
```

**Comment by plfiorini** [comment]
With CMake it's just easier to pass the installation paths to `cmake` and run the app from the installation directory. So the bug is really in the documentation.

**Comment by plfiorini** [comment]
@magnus-gross Do you think https://github.com/lirios/fluid/commit/eb3efc3268bcdcdd8a12c9a1c42514db1caf21df is enough for your needs?

**Comment by magnus-gross** [comment]
I think that is enough for now. I was kinda hoping that `cmake` would allow bundling everything into the final binary (e.g. such that you could copy the binary into another directory and it would run fine without missing imports), but since `qmake` does not support that either, I think this is fine.

Maybe `linuxdeployqt` can achieve the single binary file thing...
