### ISSUE TITLE
Support qtquickcompiler

### ISSUE THREAD

**Issue by vimpostor** [lirios/fluid#282]
It would be cool, if there was a simple way to enable the qtquickcompiler for Fluid.

Maybe enable it for Release builds like this:
```javascript
CONFIG(debug, debug|release) {
	message("Running debug build")
}

CONFIG(release, debug|release) {
	message("Running release build")
	CONFIG += qtquickcompiler
}
```

I tried to enable the qtquickcompiler from the top level subdirs qmake project, by using `CONFIG += qtquickcompiler`, but it seemed to have no effect at all, and when I put it into the `src/src.pro` it seems to have no effect for Fluid, just for my own QML files.

Do you know any way to enable the qtquickcompiler for Fluid, when using it from an project?

You can test, if the qtquickcompiler is working, by putting nonsense into a QML file and seeing if it finds the errors at compile time:
```qml
// beginning of a qml file
nonsense to trigger qtquickcompiler

// ...
import QtQuick 2.12
```

When I put nonsense into my own QML files, it is detected at compile time, but if I put it into Fluid files, it is detected at runtime. So, I have to assume that the qtquickcompiler is not working for Fluid automatically.

Is there any way to enable it for Fluid?

This would improve performance and startup time.

**Comment by soheilarmin** [comment]
qtquickcompiler looks into resources to compile .qml files and these files are not included in the qrc resources for Fluid.

**Comment by plfiorini** [comment]
QtQuickCompiler requires at least Qt 5.11, might as well raise the requirement to Qt 5.12 LTS.
I'm looking into it, testing with Liri Shell first.
Adding support to cmake-shared to automatically use the compiler if found: https://github.com/lirios/cmake-shared/issues/6

**Comment by plfiorini** [comment]
This now happens automatically besides we had something implemented within cmake-shared.

See https://doc.qt.io/qt-6/qtqml-qtquick-compiler-tech.html#the-qml-script-compiler
