### ISSUE TITLE
Item 'bundle' is not declared

### ISSUE THREAD

**Issue by christopherwoo** [lirios/fluid#285]
## Expected Behavior
Build fluid-demo using qbs

## Current Behavior
Error: src/demo/demo.qbs:7:5 Item 'bundle' is not declared. Did you forget to add a Depends item?

## Steps to Reproduce (for bugs only)

Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant.

1. cd fluid
2. git submodule update --init --recursive
3. qbs -d build -j $(nproc) profile:qt-5-10-0 qbs.architecture:x86_64
4. error occurs.

## Context
I try to build the demo using win10-qtcreator4.8.1-qt-5.12.1, and it works. But on linux, it failed.
Can someone change qbs to qmake/cmake? [Qbs has been deprecated.](https://blog.qt.io/blog/2018/10/29/deprecation-of-qbs/)

## Environment
OS: Ubuntu 18.04
QT: 5.10.0
QBS: 1.13

**Comment by plfiorini** [comment]
Qbs support is no longer maintained, see c16e5e04e0177fd58348aca90f9db17c6847eb54
We use CMake now.

**Comment by christopherwoo** [comment]
The develop branch has a CMakeLists.txt, README.md suggests to use master branch, please add a CMakeLists.txt to master branch.

The issue change to [#283 ](https://github.com/lirios/fluid/issues/283), close this now.
