### ISSUE TITLE
Add qpm package manager support

### ISSUE THREAD

**Issue by daljit97** [lirios/fluid#293]
Hi, this project is quite useful but I would really love if it could be configured more easily. I would like if it could be integrated in [qpm](https://www.qpm.io). Is there any possibility for this?

**Comment by plfiorini** [comment]
qpm has some bizarre requirements such as reverse DNS names like `io.liri.Fluid.Controls` rather than `Fluid.Controls`.  We have to evaluate the impact of this and other changes impose by qpm.

**Comment by plfiorini** [comment]
I'm open to explore the possibility, if it wasn't clear.

**Comment by plfiorini** [comment]
Qpm is dead, see: https://github.com/Cutehacks/qpm
