### ISSUE TITLE
Error when building on android with qmake

### ISSUE THREAD

**Issue by shoks** [lirios/fluid#300]
hi have errors when building it on android it is generating a messed up Makefile

makefile: 

install_target: first FORCE
	@test -d D:$(INSTALL_ROOT:@msyshack@%=%)/Qt/5.13.2/android_armv7/qml/Fluid/Controls || mkdir -p D:$(INSTALL_ROOT:@msyshack@%=%)/Qt/5.13.2/android_armv7/qml/Fluid/Controls
	-$(QINSTALL_PROGRAM) ../../../qml/Fluid/Controls/$(TARGET) D:$(INSTALL_ROOT:@msyshack@%=%)/Qt/5.13.2/android_armv7/qml/Fluid/Controls/$(TARGET)

Error copying ../../../qml/Fluid/Core/libfluidcoreplugin.so to D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/libfluidcoreplugin.so: Cannot create D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/libfluidcoreplugin.so for output
make[4]: [install_target] Error 3 (ignored)
D:/Qt/5.13.2/android_armv7/bin/qmake.exe -install qinstall D:/dev/prime_events/app/fluid/src/imports/core/qmldir D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/qmldir
Error copying D:/dev/prime_events/app/fluid/src/imports/core/qmldir to D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/qmldir: Cannot create D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/qmldir for output
make[4]: [install_qmldir] Error 3 (ignored)
D:/Qt/5.13.2/android_armv7/bin/qmake.exe -install qinstall D:/dev/prime_events/app/fluid/src/imports/core/plugins.qmltypes D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/plugins.qmltypes
Error copying D:/dev/prime_events/app/fluid/src/imports/core/plugins.qmltypes to D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/plugins.qmltypes: Cannot create D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/plugins.qmltypes for output
make[4]: [install_qmlfiles] Error 3 (ignored)
D:/Qt/5.13.2/android_armv7/bin/qmake.exe -install qinstall D:/dev/prime_events/app/fluid/src/imports/core/Object.qml D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/Object.qml
Error copying D:/dev/prime_events/app/fluid/src/imports/core/Object.qml to D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/Object.qml: Cannot create D:D:/dev/prime_events/build-prime_event-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/android-build/Qt/5.13.2/android_armv7/qml/Fluid/Core/Object.qml for output
make[4]: [install_qmlfiles] Error 3 (ignored)

**Comment by plfiorini** [comment]
Closing because we now use cmake with Qt 6 and everything might be changed, so this issue is not relevant anymore.,
