### ISSUE TITLE
icons of minimalqmake not displaying with Qt 5.14.2

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#312]
## Expected Behavior

The (+) icon on top right of the App should display

## Current Behavior

The (+) icon on top right of the App does not display, instead a round
area revealed on pressing is displayed.

Below may be relevant:
https://codereview.qt-project.org/c/qt/qtbase/+/270573

## Steps to Reproduce (for bugs only)
1. clone fluid
2. cd to  minimalqmake folder
3. inside minimalqmake clone fluid again
4. open minimalqmake.pro in QtCreator
5. In Project setting generate Android template files.
6. Build and Run on an android mobile.

## Context

My App was running fine in 5.12 version of Qt. for somereason 
i had to upgrade to Qt 5.14 ( I needed the ability to set httpUserAgent for
WebView at is available only on 5.14).

## Environment

* Version used:  Qt 5.14
* Operating system and version: Linux Ubuntu 18.04
* Device: Smasung Note5 
![WhatsApp Image 2020-05-24 at 16 06 45](https://user-images.githubusercontent.com/7461305/82752305-b72f8e80-9dda-11ea-8384-26c41c807ba3.jpeg)

# Device Logs
```
D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
V InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@b75cee nm : org.qtproject.example ic=null
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/more_vert.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/content/add.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/arrow_back.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/more_vert.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/arrow_back.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/content/add.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/more_vert.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/arrow_back.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/content/add.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Cannot open: file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg
D 
```

**Comment by rmallah** [comment]
### Possible workaround 
CONFIG += fluid_resource_icons  
in an appropriate place will include the icons are resource.
(i am not sure which is the best place to enable fluid_resource_icons   into CONFIG)

![WhatsApp Image 2020-05-24 at 16 38 37](https://user-images.githubusercontent.com/7461305/82752668-3c1ba780-9ddd-11ea-8186-93c1f2a45c73.jpeg)

**Comment by plfiorini** [comment]
The icons are probably searched in the wrong place, given the following error:

file:///data/app/org.qtproject.example-1/lib/arm/icons/navigation/close.svg

**Comment by rmallah** [comment]
I am having to set 
CONFIG += fluid_resource_icons
in src/imports/controls/controls.pro
which is not beautiful. I tried setting it in the
non fluid .pro files of the project but it looks like
the config key is not percolated down there.

**Comment by edips** [comment]
Unfortunately I also have to use Qt 5.14.2 and I have the same problem.

**Comment by plfiorini** [comment]
Closing this issue because qmake is no longer supported
