### ISSUE TITLE
FluidControls.FloatingActionButton does not work -( due to Fluid.Effects not getting installed ) (Qt 5.14.2)

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#317]
## Expected Behavior

Application should render a FloatingActionButton(FAB) in response to inclusion 
of relevant code in qml file. an example code derived from mimalqmake example is 
below:

in: main.qml we add FAB as below inside Page1 { }
```
 Page1 {
                anchors.fill: parent

                FluidControls.FloatingActionButton {
                    anchors.centerIn: parent
                    text: pressed ? "Pressed!" : "Press"
                    mini: false
                    width: 100
                    height: 100
                }
            }
```

## Current Behavior

The current behaviors is that on android the main.qml page does not
load properly and the user is displayed with a blank page.
Where as the same code  renders fine on Desktop/Linux

The error in the run console states:
```
W libsrc_armeabi-v7a.so: QQmlApplicationEngine failed to load component
W libsrc_armeabi-v7a.so: qrc:/main.qml:31:17: Type FluidControls.FloatingActionButton unavailable
W libsrc_armeabi-v7a.so: qrc:/android_rcc_bundle/qml/Fluid/Controls/FloatingActionButton.qml:22:1: module "Fluid.Effects" is not installed

```

## Possible Solution
Sorry i am at loss.

## Steps to Reproduce (for bugs only)

Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant.
The problem is replicable in per-project installation scenario.

1. create a shiny new folder "scratch"
2. cd scratch
3. git clone https://github.com/lirios/fluid.git 
4. cd fluid/examples/perproject/minimalqmake/
5.  git clone https://github.com/lirios/fluid.git   [ clone again ]
6. open minimalqmake.pro in qtcreator 
7. create android templates in project settings.
8. Modify main.qml as per original problem statement.
9. Run on the mobile android device.
10. keep an watch on the application output tab.
11. the page instead of showing controls will should blank on the mobile.

## Context

In my app based on fluid we use FAB. Such pages are not loading an cause
quite of lot of problem.

## Environment

Include as many relevant details about the environment you experienced the bug in.

* Version used: Qt 5.14.2 (Latest)
* Operating system and version:  Linux Ubuntu 18.04
* Device (phone, tablet, laptop, desktop, ...):  Samsung Android Version: 7.0 (Nougat)
* CPU, RAM, screen resolution:  Quadcode , 4 GB, 1080x1920

**Comment by plfiorini** [comment]
Closing because we now use cmake with Qt 6, no more separate modules, and everything might be changed, so this issue is not relevant anymore.
