### ISSUE TITLE
minimalqmake with windows

### ISSUE THREAD

**Issue by Simon-12** [lirios/fluid#323]
Hey,

i tried to get the minimalqmake exmaple running. 
Build shows no problems, when i press the start button i get the following message:

```
QQmlApplicationEngine failed to load component
qrc:/main.qml:5:1: module "Fluid.Controls" is not installed
```

If i open the main.qml file from the example, the import path is found but Qt Creator shows me the messeage on line 7:

`
FluidControls.ApplicationWindow {    -> Prototype Cycle, the last non repeated element error (M303)
`

With googlin i don't get a solution or can't find anything useful. I also tried with cmake, with no success.
Did i miss something?

Environment
* Version used: Qt 5.15.0 MSVC2019 64bit
* Operating system and version: Windows 10 64bit
* Device: Desktop

Thanks for your work

**Comment by plfiorini** [comment]
qmake is not going to be supported anymore for Fluid 2
