### ISSUE TITLE
prototype cycle, the last non-repeated component is "ApplicationWindow11". (M303)

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#331]
## Expected Behavior

There should not be any warning in code editor

## Current Behavior
The code editor displays warning.
```
prototype cycle, the last non-repeated component is "ApplicationWindow11". (M303)
```
## Context

We are trying to compile mimalqmake example.

## Environment

Include as many relevant details about the environment you experienced the bug in.

* Version used: 
* Operating system and version:  Mac Monterey
* Device : Desktop
* Qt 15.12.2 Qt Creator: 5.0.1

<img width="922" alt="image" src="https://user-images.githubusercontent.com/7461305/233851404-d303af8e-1260-40a5-83cb-74b1336b0300.png">

*

**Comment by plfiorini** [comment]
Fluid 1.x is closed, all development effort is going into 2.0 which won't have this issue so I'm closing this issue.
