### ISSUE TITLE
Fluid.Controls module not found (only QtCreator) when FLUID_LOCAL

### ISSUE THREAD

**Issue by SboichakovDmitriy** [lirios/fluid#47]
Guys, I already setup QML_IMPORT_PATH var in .pro file
Any else module found by this way (include Fluid.Core and etc) but Fluid.Controls - nope.
Any ideas?

**Comment by IlyaBizyaev** [comment]
Same problem.

**Comment by plfiorini** [comment]
I did an experiment in feature/local and found out how to make QtCreator see the the import but then it doesn't see the properties. Postpone to 0.11.0 for further investigation.
Please note that while this is annoying it doesn't prevent you from using the library.

**Comment by plfiorini** [comment]
More in depth analysis in #103

**Comment by plfiorini** [comment]
Closing, see #103
