### ISSUE TITLE
The demo doesn't work

### ISSUE THREAD

**Issue by SushiTee** [lirios/fluid#70]
There are a couple of issues:

- When using MSVC to build the project the linker complains about linking to the QSvgRenderer. Compiling with Windows Runtime works though (only debug).
- in Fluid/Controls Dilog.qml is missing
- After the app starts it says: qrc:/main.qml:23 Type FluidWindow unavailable

Cheers

**Comment by plfiorini** [comment]
@SushiTee 0.9.0 release tarball or develop?

**Comment by SushiTee** [comment]
develop

The SVG problems could be solved by adding "svg" to QT in the .pro file.
The Dialog.qml should be just removed from the .qrc and many files are missing there it seems.

**Comment by plfiorini** [comment]
Added missing files and removed Dialog, will test it this evening

**Comment by plfiorini** [comment]
Also, added QT += svg to core.pri

**Comment by SushiTee** [comment]
Some things were still not working and I tried to fix them (see pull request).
The SVG renderer couldn't open the svg files with _qrc:/.._ with just _:/.._ it works
