### ISSUE TITLE
Ideas behind UX

### ISSUE THREAD

**Issue by Ximik** [lirios/fluid#76]
Hello. I've found your project really cool and want to develop some basic software (image viewer, document reader) for it, but i havn't found any guidelines. E.g. i've checked files manager, but it seems like there is no multiselection, DnD and right click. Is it the idea your project is going (it's tablet/mobile-only) or it's just unimplemented yet.

Thanks.

**Comment by TheCom3di4n** [comment]
Liri's goal is to create a OS and apps for desktop with modern design. Therefore it follows the [Material Design guidelines](https://material.io/). To reach this, [Fluid](https://github.com/lirios/fluid) is being developed, which implements the MD guidelines. Even though a lot of components are already implemented, many are still missing as you can see under the [feature tag](https://github.com/lirios/fluid/labels/feature).

Currently, the majority of the software of the Liri organization is in a very early alpha state, so some features have not yet been implemented.
