### ISSUE TITLE
DatePicker calendar view and DatePickerDialog

### ISSUE THREAD

**Issue by plfiorini** [lirios/fluid#77]
https://material.io/guidelines/components/pickers.html#pickers-date-pickers

**Comment by crutchcorn** [comment]
Please wait. [The current spec is mobile only](https://github.com/angular/material2/issues/75)

**Comment by plfiorini** [comment]
@crutchcorn what's so mobile specific that cannot work on desktops?

**Comment by tim-sueberkrueb** [comment]
@plfiorini Maybe we could allow editing dates/numbers manually to make it more desktop-friendly?

**Comment by plfiorini** [comment]
@tim-sueberkrueb a regular TextField with proper validator would be enough but that's a separate component

**Comment by plfiorini** [comment]
Also the calendar view itself should be a DatePicker component that you can use where you want while DatePickerDialog is just a preconfigured dialog with proper sizing.

**Comment by crutchcorn** [comment]
I my not be a MD official, but here's my guess:
It involves too much swiping and mobile based gestures. I think a calendar view based solution would be best. The less clicks and gestures needed the better

**Comment by crutchcorn** [comment]
Sorry, link was bad. Updated

**Comment by oKcerG** [comment]
It doesn't require swiping though, clicking the arrows to change the month and clicking the year to switch to year view can easily be done with a click.
I agree that it should at least on desktop be an editable textfield with an action icon (downward chevron or calendar icon) to pop up the picker.

**Comment by plfiorini** [comment]
That's true but in my opinion the date picker is still usable on the desktop since you can press the left and right arrows, instead the year picker (or the time picker for that matters) is entirely gesture based.

**Comment by plfiorini** [comment]
Let's turn this issue into an Epic and break down to smaller tasks

**Comment by crutchcorn** [comment]
But it does, if you're following spec anyway; You have separate pages of date and years. This separation is not spatially wise on anything but mobile. Honestly the year field should be expanded to a dropdown, and the card should expand out IMO. See how the time picker expands on desktop
![](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B3321sZLoP_HREpvc2hIX210OVE/components_pickers_time2.png)
See how it expands out to have both on one page? That's being wise of your space and respecting the developers to do good with that space to make room for it

**Comment by automatedenergy** [comment]
Military time in a 0 -23 hr dropdown, and minutes in a 0-59 dropdown. Slider is nice.

**Comment by oKcerG** [comment]
md-datepicker was merged on 12 May : https://github.com/angular/material2/pull/4404
Overview in the doc : https://material.angular.io/components/datepicker

The official guidelines are still unchanged though.

**Comment by magnus-gross** [comment]
This one here could be helpful too: https://forum.qt.io/topic/82700/datepicker-anyone/
