### ISSUE TITLE
Visual Studio 2015 Build

### ISSUE THREAD

**Issue by alexanderlinne** [lirios/fluid#79]
Hello.

I currently try to build fluid as an Visual Studio 2015 project.
My attempt was to just import fluid.pri using the Qt VS Tools and build it, but I get the error:
    "moc: Too many input files specified: [...]"
on each file in the project.

Any ideas?

**Comment by plfiorini** [comment]
You should either include fluid.pri in your qmake project or build Fluid as a system library using cmake.

**Comment by microneo** [comment]
I get an error when building using cmake:
 
>  Could not find a package configuration file provided by "ECM" (requested
>   version 1.7.0) with any of the following names:
> 
>     ECMConfig.cmake
>     ecm-config.cmake
I can't buld ECM on windows.. Also i can't  find tutorial how build ecm..
