### ISSUE TITLE
QT5.8 Fedora

### ISSUE THREAD

**Issue by Collinthegeek** [lirios/fluid#80]
I've been trying to build on Fedora but I can't find cmake-qt5 version 5.8.

Here's the error:

>$ cmake .. -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
>-- Could not set up the appstream test. appstreamcli is missing.
>CMake Error at CMakeLists.txt:53 (find_package):
> Could not find a configuration file for package "Qt5" that is compatible
>  with requested version "5.8.0".
>
>  The following configuration files were considered but not accepted:
>
>    /usr/lib64/cmake/Qt5/Qt5Config.cmake, version: 5.6.2
>   /lib64/cmake/Qt5/Qt5Config.cmake, version: 5.6.2
>
>
>-- Configuring incomplete, errors occurred!

**Comment by plfiorini** [comment]
Fedora 24 has still Qt 5.6.2 not Qt 5.8.0 so it doesn't meet the minimum version requirements.
