### ISSUE TITLE
Qt Quick 

### ISSUE THREAD

**Issue by microneo** [lirios/fluid#81]
In design i get error : Qt Quick emulator layer crashed. 
Fluid supported in a Qt quick disign?

**Comment by tim-sueberkrueb** [comment]
@microneo I don't think Fluid works in QtCreator Design. 
@plfiorini is it supposed to work?

**Comment by microneo** [comment]
@tim-sueberkrueb I realized that the Qt designer is unstable. I don't think that fluid will work here. So the question is settled...

**Comment by plfiorini** [comment]
Not implemented yet but it would be nice to have

**Comment by tim-sueberkrueb** [comment]
@microneo see #86.
