### ISSUE TITLE
Hover effects and tooltips don't work in appBar of page set to ApplicationWindow's initialPage property

### ISSUE THREAD

**Issue by Aldrog** [lirios/fluid#88]
In QtQuick, `hoverEnabled` property is derived from item's parent. Because of [this line](https://github.com/lirios/fluid/blob/develop/src/imports/controls/Page.qml#L131) `appBar` has it set to `false` unless page has been pushed to a PageStack which doesn't happen for ApplicationWindow's `initialPage`.

**Comment by yangxingpping** [comment]
Try setting the `QT_QUICK_CONTROLS_HOVER_ENABLED` environment variable.

**Comment by Aldrog** [comment]
@yangxingpping no, it doesn't help here, it only enables/disables hover effects in general.
Even if it worked the other way it wouldn't be a good solution. This needs a fix on Fluid side.

**Comment by Aldrog** [comment]
Actually, a valid workaround ATM is pushing to a `pageStack` on `Component.onCompleted` instead of setting `initialPage`.

**Comment by yangxingpping** [comment]
@Aldrog I'm agree with you.  I did not even build it success on win10 or Ubuntu without modify  hierarchy of the files. #87 , How did you achive it?

**Comment by Aldrog** [comment]
@yangxingpping I did
```sh
mkdir build
cd build
qmake \
    CONFIG+=use_qt_paths \
    CONFIG-=create_prl \
    ..
make
sudo make install
```
It was on Arch Linux but should work on any other Linux distro as well.

**Comment by yangxingpping** [comment]
@Aldrog  It didn't work on windows.
