### ISSUE TITLE
Fluid.Controls not found in demo

### ISSUE THREAD

**Issue by St1rling** [lirios/fluid#91]
I've built after cloning from the repository and am getting the above error.

**Comment by plfiorini** [comment]
@St1rling what error?

**Comment by magnus-gross** [comment]
Probably related to #84

**Comment by motters** [comment]
This happens if you are opening "src/demo/demo.pro" and not "fluid-demo.pro" in Qt.

In short make sure your opening fluid-demo.pro in the root of the repo in Qt :)

**Comment by plfiorini** [comment]
Closing for spring cleaning, please chime in if you still have problems.

**Comment by St1rling** [comment]
It's all fixed, thanks :)
