### ISSUE TITLE
Can't run demo on windows

### ISSUE THREAD

**Issue by orzel1244** [lirios/fluid#95]
Hello, I found this repo, that's cool, but I can't run it :/ I tried to run demo but got this error: 
`No rule to make target 'C:/fluid/fluid/icons/icons.qrc', needed by '.rcc/debug/qrc_icons.cpp'.  Stop.`
Also, could you provide installation tutortial for windows?
Thanks.

**Comment by plfiorini** [comment]
Probably you didn't run the script https://github.com/lirios/fluid/blob/develop/scripts/fetch_icons.sh from the root, am I right?

**Comment by orzel1244** [comment]
.Sh won't worki on windows i think


20.04.2017 9:05 PM "Pier Luigi Fiorini" <notifications@github.com>
napisał(a):

Probably you didn't run the script https://github.com/lirios/
fluid/blob/develop/scripts/fetch_icons.sh from the root, am I right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lirios/fluid/issues/95#issuecomment-295861532>, or mute
the thread

**Comment by plfiorini** [comment]
It's possible but you need a bash shell around so it might be annoyting.
Filed #96 to rewrite the script in the qmake project although it requires having `git` in the PATH which is a much more attainable goal.
